---
config:
  layout: elk
  theme: neutral
---
erDiagram
  instance_request {
    Int id
    String title
    String hostname
    String description
    instance_request_type type
    Int cpus
    Int memory
    Int disk
    request_state state
    String reason
    DateTime created_at
    DateTime updated_at  
  }
  instance {
    Int id
    String title
    String hostname
    String description
    instance_request_type type
    Int cpus
    Int memory
    Int disk
    instance_state state
    instance_status status
    Int vm_id
    DateTime created_at
    DateTime updated_at
    DateTime deleted_at  
  }
  instance_request_extends {
    Int id
    String title
    String description
    request_state state
    String reason
    DateTime created_at
    DateTime updated_at  
  }