---
config:
  layout: elk
  theme: neutral
---
erDiagram
  network {
    Int id
    String name
    String network
    String gateway
    DateTime created_at
    DateTime updated_at
    DateTime deleted_at  
  }
  ip_address {
    Int id
    String ip
    DateTime created_at
    DateTime updated_at
    DateTime deleted_at  
  }