FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json bun.lock ./
COPY apps/midori/package.json ./apps/midori/

# Copy source code
COPY . .

# Install dependencies
RUN bun install --frozen-lockfile

# Build the application
ENV NODE_ENV=production
RUN cd apps/midori && bun run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

ARG API_URL
ENV API_URL=${API_URL}

ARG FRONTEND_BASE_URL
ENV FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-http://localhost:3000}

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=base /app/apps/midori/public ./public
COPY --from=base --chown=nextjs:nodejs /app/apps/midori/.next/standalone ./.next/standalone

USER nextjs
EXPOSE 3000

CMD ["node", ".next/standalone/apps/midori/server.js"]
