service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporter: [prometheus]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: trace_store
      metric_storage: prometheus
    ui:
      config_file: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      trace_store:
        elasticsearch:
          server_urls:
            - "http://trace_store:9200"
          indices:
            index_prefix: "jaeger-traces"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            services:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            dependencies:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            sampling:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
        badger:
          directory: "/var/lib/jaeger/badger"
          max_age: "7d"
      trace_store_archive:
        elasticsearch:
          server_urls:
            - "http://trace_store:9200"
          indices:
            index_prefix: "jaeger-traces-archive"
        badger:
          directory: "/var/lib/jaeger/badger-archive"
          max_age: "30d"
    metric_backend:
      metric_storage:
        prometheus:
          endpoint: "http://prometheus:9090"

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: trace_store
