import type { Metadata } from "next";

import "@midori/styles/globals.css";
import { ThemeProvider } from "@midori/contexts/theme";

export const metadata: Metadata = {
  title: "FITM Cloud-based Platform",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <ThemeProvider>
        {children}
      </ThemeProvider>
    </html>
  );
}
