global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['tracing:8888']
  
  - job_name: 'loki'
    static_configs:
      - targets: ['logging:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['monitoring:3000']
  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
  
  - job_name: 'database'
    static_configs:
      - targets: ['db:5432']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093